openapi: 3.0.4
info:
  title: Unified Notification Service v0.1 - PSO
  version: 'v0.1'
  description: Work in progress
servers:
  - url: /api

securitySchemes:
  MutualTLS:
    type: mutualTLS
    description: Mutual TLS authentication for secure API communication.

security:
  - MutualTLS: []

paths:
  /status:
    get:
      summary: Gets service status
      operationId: getStatus
      security: []
      tags:
        - MVP
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '500':
          description: Internal server error
        default:
          description: Unexpected error

  /send:
    post:
      summary: Sends notifications
      operationId: postMessage
      tags:
        - MVP
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              maxItems: 10
              items:
                $ref: '#/components/schemas/MessageRequest'
        required: true
      responses:
        '202':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 10
                items:
                  $ref: '#/components/schemas/MessageRequestResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: Internal server error
        default:
          description: Unexpected error

  /status/{notificationID}:
    get:
      summary: Gets status of notification
      operationId: getNotificationStatus
      tags:
        - MVP
      parameters:
        - name: notificationID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 10
                items:
                  $ref: '#/components/schemas/MessageStatus'
        '500':
          description: Internal server error
        default:
          description: Unexpected error
components:
  schemas:
    Status:
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
    MessageRequest:
      type: object
      required:
        - DepartmentID
        - NotificationID
        - UserID
        - NotificationTitle
        - NotificationBody
      properties:
        DepartmentID:
          type: string
          description: ID of department sending notification
        NotificationID:
          type: string
          description: ID of the notification to be used for idempotency & analytics
        UserID:
          type: string
          description: ID of the recipient fetched from UDP
        NotificationTitle:
          type: string
          description: Title of the notification to be displayed on mobile device
        NotificationBody:
          type: string
          description: Contents of the notification to be displayed on push notification
        MessageTitle:
          type: string
          description: (Optional) Title of the message displayed in the GovUK app's notification centre, falls back on notification title
        MessageBody:
          type: string
          description: (Optional) Contents of the message displayed in the GovUK app's notification centre, falls back on notification body
        DeeplinkURL:
          type: string
          description: Deeplink url to show the notification centre
    MessageRequestResponse:
      type: object
      properties:
        NotificationID:
          type: string
    MessageStatus:
      type: object
      required:
        - NotificationID
        - Status
      properties:
        NotificationID:
          type: string
        Status:
          type: string
          enum:
            - RECEIVED
              - VALIDATING
              - VALIDATED
              - VALIDATION_FAILED
              - PROCESSING
              - PROCESSED
              - PROCESSING_FAILED
              - DISPATCHING
              - DISPATCHED
              - DISPATCHING_FAILED
              - DELIVERED
              - NOTIFICATION_CENTRE_READ
              - NOTIFICATION_CENTRE_MARKED_AS_UNREAD
              - NOTIFICATION_CENTRE_HIDDEN
        Reason:
          type: string
          description: Provides addition context to the state

    BadRequestResponse:
      type: object
      properties:
        message:
          type: string
