name: Deployment

on:
  pull_request:
  push:
    tags:
      - v*.*.*
  # Work in progress - workflow_dispatch should allow for manual deployments and environment picker
  # # # workflow_dispatch:
  # # #   #checkov:skip=CKV_GHA_7: "GitHub Actions contain workflow_dispatch inputs parameters" - in this case parameters are locked down to environments available in GH - invalid flag.
  # # #   inputs:
  # # #     environment:
  # # #       description: 'Environment to deploy to'
  # # #       type: environment
  # # #       required: true
  # # #       default: Dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  deploy:
    environment: Dev
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: echo "Branch ref ${{ github.ref }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2
          mask-aws-account-id: true
          disable-retry: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - name: Install Dependencies
        run: npm ci

      - name: Build bundles
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform initialize
        working-directory: ./terraform/notifications
        run: terraform init -backend-config "bucket=$TF_bucket" -backend-config "key=$TF_key" -backend-config "region=$TF_region"
        env:
          AWS_REGION: ${{ vars.TF_region }}
          TF_region: ${{ vars.TF_region }}
          TF_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_key: ${{ vars.TF_key }}
          TF_env: ${{ vars.TF_env }}

      - name: Terraform plan
        working-directory: ./terraform/notifications
        run: terraform plan
