name: Linting

on:
  # Trigger the workflow on pull request
  pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # To be refactored
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - name: Install Dependencies
        run: npm ci
      # To be refactored

      - name: Run Lint Script
        run: npm run format

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Formatting
        id: fmt
        run: terraform fmt -check
